// ---------------------------------------------------------
// This file was generated by parol.
// Do not edit this file manually.
// Changes will be overwritten on the next build.
// ---------------------------------------------------------

using System;
using System.Collections.Generic;
using Parol.Runtime;
using Parol.Runtime.Scanner;

namespace FilterQueryDemo {
    /// <summary>
    /// Parser facade generated by parol for this grammar.
    /// Provides parse tables and convenience entry points.
    /// </summary>
    public class FilterQueryDemoParser {
    /// <summary>
    /// Scanner tables and helper functions generated by parol for this grammar.
    /// </summary>
    public static class FilterQueryDemoScannerData {
        /// <summary>
        /// Ordered terminal names used by scanner and parser diagnostics.
        /// </summary>
        public static readonly string[] TerminalNames = [
            "EndOfInput",
            "Newline",
            "Whitespace",
            "LineComment",
            "BlockComment",
            "OrOp",
            "AndOp",
            "NotOp",
            "LParen",
            "RParen",
            "CompareOp",
            "True",
            "False",
            "Identifier",
            "StringLit",
            "NumberLit",
            "Error",
        ];

        /// <summary>
        /// Maps an input character to its scanner character class index.
        /// </summary>
        /// <param name="c">Character to classify.</param>
        /// <returns>The class index, or <c>null</c> if no class matches.</returns>
        public static int? MatchFunction(char c) {
            var intervals = new (char Start, char End, int ClassIdx)[] {
                ('\0', '\u0008', 0),
                ('\t', '\t', 1),
                ('\n', '\n', 2),
                ('\u000b', '\u000c', 1),
                ('\r', '\r', 3),
                ('\u000e', '\u001f', 0),
                (' ', ' ', 1),
                ('!', '!', 4),
                ('"', '"', 5),
                ('#', '\'', 0),
                ('(', '(', 6),
                (')', ')', 7),
                ('*', '*', 8),
                ('+', ',', 0),
                ('-', '-', 9),
                ('.', '.', 10),
                ('/', '/', 11),
                ('0', '0', 12),
                ('1', '9', 13),
                (':', ';', 0),
                ('<', '<', 14),
                ('=', '=', 15),
                ('>', '>', 16),
                ('?', '@', 0),
                ('A', 'A', 17),
                ('B', 'C', 18),
                ('D', 'D', 19),
                ('E', 'E', 20),
                ('F', 'F', 21),
                ('G', 'K', 18),
                ('L', 'L', 22),
                ('M', 'M', 18),
                ('N', 'N', 23),
                ('O', 'O', 24),
                ('P', 'Q', 18),
                ('R', 'R', 25),
                ('S', 'S', 26),
                ('T', 'T', 27),
                ('U', 'U', 28),
                ('V', 'Z', 18),
                ('[', '[', 0),
                ('\\', '\\', 29),
                (']', '^', 0),
                ('_', '_', 18),
                ('`', '`', 0),
                ('a', 'a', 17),
                ('b', 'c', 18),
                ('d', 'd', 19),
                ('e', 'e', 20),
                ('f', 'f', 21),
                ('g', 'k', 18),
                ('l', 'l', 22),
                ('m', 'm', 18),
                ('n', 'n', 23),
                ('o', 'o', 24),
                ('p', 'q', 18),
                ('r', 'r', 25),
                ('s', 's', 26),
                ('t', 't', 27),
                ('u', 'u', 28),
                ('v', 'z', 18),
                ('{', '\u0084', 0),
                ('\u0085', '\u0085', 1),
                ('\u0086', '\u009f', 0),
                ('\u00a0', '\u00a0', 1),
                ('\u00a1', '\u017e', 0),
                ('\u017f', '\u017f', 26),
                ('\u0180', '\u167f', 0),
                ('\u1680', '\u1680', 1),
                ('\u1681', '\u1fff', 0),
                ('\u2000', '\u200a', 1),
                ('\u200b', '\u2027', 0),
                ('\u2028', '\u2029', 1),
                ('\u202a', '\u202e', 0),
                ('\u202f', '\u202f', 1),
                ('\u2030', '\u205e', 0),
                ('\u205f', '\u205f', 1),
                ('\u2060', '\u2129', 0),
                ('\u212a', '\u212a', 18),
                ('\u212b', '\u2fff', 0),
                ('\u3000', '\u3000', 1),
                ('\u3001', '\ufffe', 0),
            };

            int low = 0, high = intervals.Length - 1;
            while (low <= high) {
                int mid = low + (high - low) / 2;
                if (c >= intervals[mid].Start && c <= intervals[mid].End) return intervals[mid].ClassIdx;
                if (c < intervals[mid].Start) high = mid - 1;
                else low = mid + 1;
            }
            return null;
        }
        /// <summary>
        /// Scanner mode table consumed by the scanner runtime.
        /// </summary>
        public static readonly ScannerMode[] ScannerModes = {
            new(
                "INITIAL",
                [
                ],
                new Dfa([
                    new DfaState(
                        [ new(29), new(39), new(43), new(44), new(33), new(30), new(41), new(42), new(29), new(32), new(29), new(31), new(26), new(27), new(38), new(38), new(38), new(15), new(8), new(8), new(8), new(9), new(8), new(14), new(17), new(8), new(8), new(10), new(8), new(29) ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(3), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1) ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(3), new(1), new(1), new(6), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1) ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(3), new(1), new(1), new(36), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1), new(1) ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ new(4), new(4), new(4), new(4), new(4), new(40), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(5) ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ new(4), new(4), null, new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4) ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, new(2), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, new(28), new(28), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), null ],
                        [
                            new(13, 12, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(11), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), null ],
                        [
                            new(13, 12, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(12), new(8), new(8), new(8), null ],
                        [
                            new(13, 12, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(8), new(8), new(13), new(8), new(8), new(8), new(8), new(8), new(8), null ],
                        [
                            new(13, 12, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(19), null ],
                        [
                            new(13, 12, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(18), new(8), new(8), null ],
                        [
                            new(13, 12, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(16), new(8), new(8), new(8), new(8), null ],
                        [
                            new(13, 12, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(8), new(8), new(8), new(20), new(8), new(8), new(8), new(8), new(8), null ],
                        [
                            new(13, 12, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(23), new(8), null ],
                        [
                            new(13, 12, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(24), new(8), new(8), new(8), null ],
                        [
                            new(13, 12, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(22), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), null ],
                        [
                            new(13, 12, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(25), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), null ],
                        [
                            new(13, 12, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(21), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), null ],
                        [
                            new(13, 12, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), null ],
                        [
                            new(6, 5, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), null ],
                        [
                            new(12, 11, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), null ],
                        [
                            new(7, 6, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), null ],
                        [
                            new(5, 4, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(8), null, new(8), new(8), null, null, null, new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), new(8), null ],
                        [
                            new(11, 10, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(7), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(15, 14, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, new(7), null, new(27), new(27), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(15, 14, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, new(28), new(28), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(15, 14, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(16, 15, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ new(4), new(4), new(4), new(4), new(4), new(40), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(4), new(5) ],
                        [
                            new(16, 15, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, new(1), null, null, new(35), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(16, 15, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, new(26), new(27), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(16, 15, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, new(37), null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(16, 15, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(3, 2, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ new(35), new(35), new(34), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35), new(35) ],
                        [
                            new(3, 2, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, new(2), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(4, 3, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(10, 9, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, new(37), null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(10, 9, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, new(39), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(2, 1, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(14, 13, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(8, 7, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(9, 8, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(1, 0, new Lookahead.None()),
                        ]
                    ),
                    new DfaState(
                        [ null, null, new(43), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null ],
                        [
                            new(1, 0, new Lookahead.None()),
                        ]
                    ),
                ])
            ),
        };
    }


        /// <summary>
        /// Maximum lookahead k used by the generated grammar.
        /// </summary>
        public const int MaxK = 2;

        /// <summary>
        /// Ordered non-terminal names used by the parser tables.
        /// </summary>
        public static readonly string[] NonTerminalNames = [
            "AndExpr",
            "AndExprList",
            "AndOp",
            "BoolLit",
            "CompareOp",
            "Comparison",
            "Expr",
            "False",
            "Identifier",
            "NotOp",
            "NumberLit",
            "Operand",
            "OrExpr",
            "OrExprList",
            "OrOp",
            "Primary",
            "Query",
            "StringLit",
            "True",
            "UnaryExpr",
        ];

        /// <summary>
        /// Lookahead DFAs indexed by non-terminal index.
        /// </summary>
        public static readonly LookaheadDfa[] LookaheadAutomata = [
            /* 0 - "AndExpr" */
            new(
                6,
                [
                ],
                0 // k
            ),
            /* 1 - "AndExprList" */
            new(
                -1,
                [
                    new(0, 0, 2, 8),
                    new(0, 5, 2, 8),
                    new(0, 6, 1, 7),
                    new(0, 9, 2, 8),
                ],
                1 // k
            ),
            /* 2 - "AndOp" */
            new(
                9,
                [
                ],
                0 // k
            ),
            /* 3 - "BoolLit" */
            new(
                -1,
                [
                    new(0, 11, 1, 22),
                    new(0, 12, 2, 23),
                ],
                1 // k
            ),
            /* 4 - "CompareOp" */
            new(
                17,
                [
                ],
                0 // k
            ),
            /* 5 - "Comparison" */
            new(
                16,
                [
                ],
                0 // k
            ),
            /* 6 - "Expr" */
            new(
                1,
                [
                ],
                0 // k
            ),
            /* 7 - "False" */
            new(
                25,
                [
                ],
                0 // k
            ),
            /* 8 - "Identifier" */
            new(
                26,
                [
                ],
                0 // k
            ),
            /* 9 - "NotOp" */
            new(
                12,
                [
                ],
                0 // k
            ),
            /* 10 - "NumberLit" */
            new(
                28,
                [
                ],
                0 // k
            ),
            /* 11 - "Operand" */
            new(
                -1,
                [
                    new(0, 11, 4, 21),
                    new(0, 12, 4, 21),
                    new(0, 13, 1, 18),
                    new(0, 14, 2, 19),
                    new(0, 15, 3, 20),
                ],
                1 // k
            ),
            /* 12 - "OrExpr" */
            new(
                2,
                [
                ],
                0 // k
            ),
            /* 13 - "OrExprList" */
            new(
                -1,
                [
                    new(0, 0, 2, 4),
                    new(0, 5, 1, 3),
                    new(0, 9, 2, 4),
                ],
                1 // k
            ),
            /* 14 - "OrOp" */
            new(
                5,
                [
                ],
                0 // k
            ),
            /* 15 - "Primary" */
            new(
                -1,
                [
                    new(0, 8, 4, -1),
                    new(0, 11, 1, -1),
                    new(0, 12, 1, -1),
                    new(0, 13, 1, -1),
                    new(0, 14, 1, -1),
                    new(0, 15, 1, -1),
                    new(1, 0, 3, 14),
                    new(1, 5, 3, 14),
                    new(1, 6, 3, 14),
                    new(1, 9, 3, 14),
                    new(1, 10, 2, 13),
                    new(4, 7, 5, 15),
                    new(4, 8, 5, 15),
                    new(4, 11, 5, 15),
                    new(4, 12, 5, 15),
                    new(4, 13, 5, 15),
                    new(4, 14, 5, 15),
                    new(4, 15, 5, 15),
                ],
                2 // k
            ),
            /* 16 - "Query" */
            new(
                0,
                [
                ],
                0 // k
            ),
            /* 17 - "StringLit" */
            new(
                27,
                [
                ],
                0 // k
            ),
            /* 18 - "True" */
            new(
                24,
                [
                ],
                0 // k
            ),
            /* 19 - "UnaryExpr" */
            new(
                -1,
                [
                    new(0, 7, 1, 10),
                    new(0, 8, 2, 11),
                    new(0, 11, 2, 11),
                    new(0, 12, 2, 11),
                    new(0, 13, 2, 11),
                    new(0, 14, 2, 11),
                    new(0, 15, 2, 11),
                ],
                1 // k
            ),
        ];

        /// <summary>
        /// Production table consumed by the LL(k) parser runtime.
        /// </summary>
        public static readonly Production[] Productions = [
            // 0 - Query: Expr;
            new Production(
                16,
                [
                    new(ParseType.N, 6),
                ]
            ),
            // 1 - Expr: OrExpr;
            new Production(
                6,
                [
                    new(ParseType.N, 12),
                ]
            ),
            // 2 - OrExpr: AndExpr OrExprList /* Vec */;
            new Production(
                12,
                [
                    new(ParseType.N, 0),
                    new(ParseType.N, 13),
                ]
            ),
            // 3 - OrExprList: OrOp^ /* Clipped */ AndExpr OrExprList;
            new Production(
                13,
                [
                    new(ParseType.N, 14),
                    new(ParseType.N, 0),
                    new(ParseType.N, 13),
                ]
            ),
            // 4 - OrExprList: ;
            new Production(
                13,
                [
                ]
            ),
            // 5 - OrOp: /(?i)or/^ /* Clipped */;
            new Production(
                14,
                [
                    new(ParseType.C, 5),
                ]
            ),
            // 6 - AndExpr: UnaryExpr AndExprList /* Vec */;
            new Production(
                0,
                [
                    new(ParseType.N, 19),
                    new(ParseType.N, 1),
                ]
            ),
            // 7 - AndExprList: AndOp^ /* Clipped */ UnaryExpr AndExprList;
            new Production(
                1,
                [
                    new(ParseType.N, 2),
                    new(ParseType.N, 19),
                    new(ParseType.N, 1),
                ]
            ),
            // 8 - AndExprList: ;
            new Production(
                1,
                [
                ]
            ),
            // 9 - AndOp: /(?i)and/^ /* Clipped */;
            new Production(
                2,
                [
                    new(ParseType.C, 6),
                ]
            ),
            // 10 - UnaryExpr: NotOp UnaryExpr;
            new Production(
                19,
                [
                    new(ParseType.N, 9),
                    new(ParseType.N, 19),
                ]
            ),
            // 11 - UnaryExpr: Primary;
            new Production(
                19,
                [
                    new(ParseType.N, 15),
                ]
            ),
            // 12 - NotOp: /(?i)not/^ /* Clipped */;
            new Production(
                9,
                [
                    new(ParseType.C, 7),
                ]
            ),
            // 13 - Primary: Comparison;
            new Production(
                15,
                [
                    new(ParseType.N, 5),
                ]
            ),
            // 14 - Primary: Operand;
            new Production(
                15,
                [
                    new(ParseType.N, 11),
                ]
            ),
            // 15 - Primary: "\("^ /* Clipped */ Expr "\)"^ /* Clipped */;
            new Production(
                15,
                [
                    new(ParseType.C, 8),
                    new(ParseType.N, 6),
                    new(ParseType.C, 9),
                ]
            ),
            // 16 - Comparison: Operand CompareOp Operand;
            new Production(
                5,
                [
                    new(ParseType.N, 11),
                    new(ParseType.N, 4),
                    new(ParseType.N, 11),
                ]
            ),
            // 17 - CompareOp: /==|!=|<=|>=|<|>|=/;
            new Production(
                4,
                [
                    new(ParseType.T, 10),
                ]
            ),
            // 18 - Operand: Identifier : FilterQueryDemo::FilterIdentifier ;
            new Production(
                11,
                [
                    new(ParseType.N, 8),
                ]
            ),
            // 19 - Operand: StringLit : FilterQueryDemo::FilterString ;
            new Production(
                11,
                [
                    new(ParseType.N, 17),
                ]
            ),
            // 20 - Operand: NumberLit : FilterQueryDemo::FilterNumber ;
            new Production(
                11,
                [
                    new(ParseType.N, 10),
                ]
            ),
            // 21 - Operand: BoolLit;
            new Production(
                11,
                [
                    new(ParseType.N, 3),
                ]
            ),
            // 22 - BoolLit: True;
            new Production(
                3,
                [
                    new(ParseType.N, 18),
                ]
            ),
            // 23 - BoolLit: False;
            new Production(
                3,
                [
                    new(ParseType.N, 7),
                ]
            ),
            // 24 - True: /(?i)true/^ /* Clipped */;
            new Production(
                18,
                [
                    new(ParseType.C, 11),
                ]
            ),
            // 25 - False: /(?i)false/^ /* Clipped */;
            new Production(
                7,
                [
                    new(ParseType.C, 12),
                ]
            ),
            // 26 - Identifier: /(?i)[a-z_][a-z0-9_\.]*/;
            new Production(
                8,
                [
                    new(ParseType.T, 13),
                ]
            ),
            // 27 - StringLit: /"(\\.|[^"\\])*"/;
            new Production(
                17,
                [
                    new(ParseType.T, 14),
                ]
            ),
            // 28 - NumberLit: /-?(0|[1-9][0-9]*)(\.[0-9]+)?/;
            new Production(
                10,
                [
                    new(ParseType.T, 15),
                ]
            ),
        ];

        /// <summary>
        /// Parses input with strongly typed user actions.
        /// </summary>
        /// <param name="input">Input text to parse.</param>
        /// <param name="fileName">Logical file name used for diagnostics.</param>
        /// <param name="userActions">Typed semantic action receiver.</param>
        public static void Parse(string input, string fileName, IFilterQueryDemoActions userActions) {
            ParseInternal(input, fileName, userActions);
        }

        private static void ParseInternal(string input, string fileName, IUserActions userActions) {
            var parser = new LLKParser(
                16,
                LookaheadAutomata,
                Productions,
                FilterQueryDemoScannerData.TerminalNames,
                NonTerminalNames
            );

            var tokens = Scanner.Scan(input, fileName, FilterQueryDemoScannerData.MatchFunction, FilterQueryDemoScannerData.ScannerModes);
            parser.Parse(tokens, userActions);
        }
    }
}
